include:
  - services/backend/event-service/docker-compose.yaml
  - services/backend/client-service/docker-compose.yaml
  - services/backend/auth-service/docker-compose.yaml
  - services/backend/email-service/docker-compose.yaml
  - services/backend/gateway/docker-compose.yaml
  - rabbitmq/docker-compose.yaml
  - services/frontend/docker-compose.yaml

networks:
  shared-network:
    driver: bridge
