include:
  - services/backend/event-service/docker-compose.yaml
  - services/backend/client-service/docker-compose.yaml
  - services/backend/auth-service/docker-compose.yaml
  - services/backend/email-service/docker-compose.yaml
  - services/backend/gateway/docker-compose.yaml
  - services/backend/notification-service/docker-compose.yaml
  - services/frontend/docker-compose.yaml
  - yamls/rabbitmq/docker-compose.yaml
  - yamls/grafana/docker-compose.yaml
  - yamls/shared-redis/docker-compose.yaml

networks:
  shared-network:
    driver: bridge
