include:
  - services/rust/event-service/docker-compose.yml
  - services/rust/client-service/docker-compose.yml
  - services/rust/auth-service/docker-compose.yml
  - services/rust/email-service/docker-compose.yml

networks:
  shared-network:
    driver: bridge
