include:
  - services/rust/event-service/docker-compose.yaml
  - services/rust/client-service/docker-compose.yaml
  - services/rust/auth-service/docker-compose.yaml
  - services/rust/email-service/docker-compose.yaml
  - services/rust/gateway/docker-compose.yaml
  - services/react/docker-compose.yaml

networks:
  shared-network:
    driver: bridge
