global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:10000']
    metrics_path: /metrics

  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8080']
    metrics_path: /metrics

  - job_name: 'client-service'
    static_configs:
      - targets: ['client-service:8080']
    metrics_path: /metrics

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: /metrics

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:8080']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']
    metrics_path: /metrics
