services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-frontend:latest
    container_name: react-frontend
    ports:
      - "5000:5000"
    environment:
      - VITE_API_GATEWAY_URL=${VITE_API_GATEWAY_URL}
      - VITE_API_CLIENT_SERVICE_URL=${VITE_API_CLIENT_SERVICE_URL}
      - VITE_API_EVENT_SERVICE_URL=${VITE_API_EVENT_SERVICE_URL}
    networks:
      - shared-network
    restart: unless-stopped


